---

- name: Set roles and taints on masters nodes
  k8s:
    kubeconfig: "{{ config_base }}/admin.kubeconfig"
    api_version: v1
    kind: Node
    name: "{{ hostvars[item]['ansible_hostname'] }}"
    merge_type:
      - merge
    resource_definition:
      metadata:
        labels:
          node-role.kubernetes.io/master: ""
      spec:
        taints:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
  with_inventory_hostnames:
    - masters
  tags: label
