---

- name: Grant system:kubelet-api-admin role to kubernetes User
  k8s:
    state: present
    kubeconfig: "{{ config_base }}/admin.kubeconfig"
    resource_definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: system:kube-apiserver
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kubelet-api-admin
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: kubernetes

- name: Create PodSecurityPolicies
  k8s:
    state: present
    kubeconfig: "{{ config_base }}/admin.kubeconfig"
    resource_definition: "{{ lookup('template', 'pod-security-policy.yml.j2') }}"
