---

- name: Generate kubeconfig files
  template:
    src: kubeconfig.j2
    dest: "{{ config_base }}/{{ item.name }}.kubeconfig"
  with_items:
    - name: controller-manager
      ca: "{{ config_base }}/ca.pem"
      cert: "{{ config_base }}/controller-manager.pem"
      key: "{{ config_base }}/controller-manager-key.pem"
      server: "https://127.0.0.1:6443"
      user: "system:node:kube-controller-manager"
    - name: scheduler
      ca: "{{ config_base }}/ca.pem"
      cert: "{{ config_base }}/scheduler.pem"
      key: "{{ config_base }}/scheduler-key.pem"
      server: "https://127.0.0.1:6443"
      user: "system:kube-scheduler"
    - name: admin
      ca: "{{ config_base }}/ca.pem"
      cert: "{{ config_base }}/admin.pem"
      key: "{{ config_base }}/admin-key.pem"
      server: "https://{{ kube_apiservice_external_fqdn }}:6443"
      user: system:node:kube-admin
