---

- name: Create systemd unit files / {{ nodename }}
  template:
    src: "{{ item }}.service.j2"
    dest: "{{ config_base }}/{{ item }}-{{ nodename }}.service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Create encryption-key.yml file
  template:
    src: encryption-config.yml.j2
    dest: "{{ config_base }}/encryption-config.yml"
  vars:
    keyfile: "{{ config_base }}/encryption-key.txt"
  run_once: yes
